version: 2
updates:
- package-ecosystem: nuget
  directory: "/vol-01/lesson-1/src/basic-send"
  schedule:
    interval: daily
    time: '04:00'
- package-ecosystem: nuget
  directory: "/vol-01/lesson-2/src"
  schedule:
    interval: daily
    time: '04:00'
- package-ecosystem: nuget
  directory: "/vol-01/lesson-3/src"
  schedule:
    interval: daily
    time: '04:00'
- package-ecosystem: nuget
  directory: "/vol-01/lesson-4/src"
  schedule:
    interval: daily
    time: '04:00'
- package-ecosystem: nuget
  directory: "/vol-02/lesson-4/src"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
