version: 2
updates:
- package-ecosystem: nuget
  directory: "/volume-01/src"
  schedule:
    interval: daily
    time: '04:00'
- package-ecosystem: nuget
  directory: "/volume-02/src"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
