version: 2
updates:
- package-ecosystem: nuget
  directory: "/01-basic-send/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/02-req-resp/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/03-req-multi-resp/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/04-basic-pub-sub/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/05-pub-multi-sub/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/06-cmd-events/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/07-cmd-events-recoverability/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/08-basic-saga/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/09-timeouts/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/10-composition/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/11-decomposition/src"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/12-cart-lifecycle/src"
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
